georgringer/t3monitoring

- Classes/Service/Import/ClientImport.php
The report contains the message 'OK' when getUrl was successful.
> [BUGFIX] Fix status of client import when successful

- Classes/Controller/BaseController.php
- Resources/Private/Language/locallang.xlf
Own label for "Edit client" button
> Label for "Edit client" button

- Resources/Private/Templates/Client/Show.html
- Resources/Private/Templates/Core/List.html
- Resources/Private/Templates/Statistic/Administration.html
- Resources/Private/Templates/Statistic/Index.html
- switch to inline SVG for button icons
- use fix width for font icons
> [TASK] Optimize icon usage

- Resources/Private/Language/locallang.xlf
this was already correct:
nl.locallang.xlf
de.locallang.xlf
only here it is missing
locallang.xlf
> [BUGFIX] Add missing locallang config for update.available

- Classes/Domain/Repository/StatisticRepository.php
Fix https://github.com/georgringer/t3monitoring/issues/86
> [BUGFIX] Deactivated clients will shown in results #86

- Resources/Private/Templates/Client/Show.html
> [FEATURE] Mark insecure but unloaded extension red #75

- Resources/Private/Templates/Client/Show.html
- Resources/Private/Templates/Core/List.html
- Resources/Private/Templates/Statistic/Index.html
Make it yellow not green in Core versions if they are secure but not latest
> [Task] add warning to core version if there is an newer version

- Classes/Domain/Model/Client.php
- Classes/Service/Import/ClientImport.php
- Configuration/TCA/tx_t3monitoring_domain_model_client.php
- Resources/Private/Language/locallang.xlf
- ext_tables.sql
> [FEATURE] Add support for BasicAuth

- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/locallang_db.xlf
- Resources/Private/Templates/Statistic/Index.html
rearrange the errorMessage and the Domain
> Feature status

- Classes/Domain/Repository/ExtensionRepository.php
> [BUGFIX] Let extension filter work again

- .travis.yml
- composer.json
This should fix the failing CI (please always check if it is failing / red or green, the email notifications are there for a good reason ;-) ).
> [TASK] Update the path for the core unit tests

- Configuration/TCA/tx_t3monitoring_domain_model_client.php
Remove duplicate TCA option `tx_t3monitoring_domain_model_client.force_ip_resolve.config.default`
Related: #160
> [FOLLOWUP][FEATURE] Extend connection options for clients

- Classes/Domain/Model/Dto/EmMonitoringConfiguration.php
- Classes/Service/Import/ClientImport.php
- ext_conf_template.txt
- ext_tables.sql
Sorry for Double PR, I deleted the source branch an want to update the labels
> [FEATURE] Add configuration option to delay unreachable email

- Classes/Controller/BaseController.php
Backend-Error when opening Module.
> [BUGFIX] Wrong Namespace of Backend-UriBuilder

- Classes/Controller/BaseController.php
- Classes/ViewHelpers/EditRecordViewHelper.php
> [BUGFIX] Fix returnUrls used in Backend

- Classes/Service/Import/ClientImport.php
Fixes #199
Not sure what the title is needed for anyway.
> [BUGFIX] Set default title for mm relation of title is empty

- Classes/Domain/Repository/ClientRepository.php
> Filter by tag independent from tag position

- .gitignore
- Classes/Service/DataIntegrity.php
- Classes/Service/Import/ExtensionImport.php
Fixes updating extension list and resetting state "is_latest" for extensions.
Fixes #210 and #211 and probably #208.
> [BUGFIX] #210 and #211

- Classes/Service/Import/ClientImport.php
- Classes/Service/Import/ExtensionImport.php
More undefined array-key-fixes caused by php8
> [TASK] Fix undefined array-key in import

- Classes/Domain/Model/Client.php
- Configuration/TCA/tx_t3monitoring_domain_model_client.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/Client/Show.html
- ext_tables.sql
> Add comment possibility to t3monitoring client

- Classes/Domain/Model/Client.php
> [BUGFIX] Fix tag property in client model
