Resources/Private/Templates/Client/Show.html
link extension key in client details to extension history similar to the list of extensions view to get faster access to the update history
=> link extension key in client details to extension history

Classes/Service/DataIntegrity.php
First update extension infos, then search next secure ones and after that update usage.
=> [BUGFIX] Processing of extension information must be reversed

Resources/Private/Templates/Client/Show.html
Client domains should be opened in a new tab and not in the frame of the TYPO3 backend.
=> Open client URL's in a new window

Classes/Service/Import/ClientImport.php
Add common HTTP headers.
This is needed to avoid issues with mod_security on the client machine (Rules 960015 and 960009) blocking requests without these headers.
=> [FEATURE] Add common HTTP headers

Configuration/TCA/tx_t3monitoring_domain_model_client.php
=> [BUGFIX] Duplicate Label "insecure_extensions" in TCA #71

Resources/Public/Css/t3monitoring.css
This fix the margin of data tables
Before:
After:
=> [BUGFIX] Fix css for data-tables in panels

Classes/Service/DataIntegrity.php
There seems to be a problem with doctrine's unique alias checker, when QueryBuilder instances are used multiple times.
The following error occured, when fetching client or extension data:
>  The given alias '`tx_t3monitoring_domain_model_extension`' is not unique in FROM and JOIN clause table. The currently registered aliases are: `tx_t3monitoring_client_extension_mm`, `tx_t3monitoring_domain_model_extension`. 
I could solve the problem by creating new QueryBuilder instances inside the `foreach` loop.
=> [BUGFIX] Use QueryBilder instances only once 

Classes/Controller/StatisticController.php, Resources/Private/Templates/Statistic/Index.html
The URLs to security news and RSS feed changed during typo3.org relaunch. In the current backend module, the feed shows all news and the link "All bulletins" opens a 404 error page.
This bugfix updates both URLs in your backend module.
=> [BUGFIX] Update security news URLs after typo3.org relaunch

Resources/Private/Templates/Statistic/Index.html
The ViewHelper `<f:link.external>` seems to have problems with https-URLs and security news from RSS feed are linked like this `http://https//typo3.org/...`
The RSS feed contains full URLs, so I think it should be save to use only `<a>` tags instead of `<f:link.external>`
=> [BUGFIX] Use <a> tag instead of <f:link.external> to not have problems with HTTPS links

Classes/Domain/Repository/ClientRepository.php, Resources/Private/Templates/Notification/AdminEmail.txt, Resources/Private/Templates/Notification/ClientEmail.txt
When doing my first steps with t3monitoring, I had instances with "extra dangers". They are red in the backend, but I did not receive any reports, which confused me.
I think, the extra are important enough to trigger report emails and should be included in the mails.
It would be great to see this in your official version.
=> [TASK] Include extra dangers in report emails

Resources/Private/Templates/Statistic/Administration.html
The IP address hint in Administration view contains `<code>` in its locallang string. This text is shown in the browser instead of rendered as HTML:
> ![before](https://user-images.githubusercontent.com/16088567/43314895-9f8dbc6a-9194-11e8-94c8-127913fb48df.png)
This pull request changes that and the IP address is shown correctly inside the `<code>` tag:
> ![after](https://user-images.githubusercontent.com/16088567/43314894-9f6477ba-9194-11e8-9c9a-590525b9572f.png)
If you have security concerns with this change, because HTML from locallang will be shown in the browser, the alternative solution could be to remove the `<code>` tag from the locallang file or replace them with quotes.
=> [BUGFIX] Update IP hint formatting in Administration view

Resources/Private/Templates/Client/Show.html
Hi Georg,
this new info is helpful to see if the current installed extension supports a Typo3/php major update.
With this I check if I have to disable extensions before a major update.
Grüße
Björn
=> [FEATURE] Show extension dependencies of installed version

ext_tables.php
When saving in TYPO3 v9 an error message is generated telling you that it is not allowed to save the record. This error has been fixed with my change.
=> TYPO3 v9: Error during the saving process

Classes/Domain/Model/Client.php, Configuration/TCA/tx_t3monitoring_domain_model_client.php, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/Client/Show.html, Resources/Private/Templates/Statistic/Index.html, ext_tables.sql
Allow clients to have multiple tags. Related issue: #133 
The tag column must be migrated via the important actions compare database wizard.
=> [FEATURE] Update client model to support multiple tags

README.rst
The t3monitoring_client provides the data not the day. On first read it was a bit confusing.
=> Change what is provided by the extension

Configuration/TCA/tx_t3monitoring_domain_model_extension.php, ext_tables.sql
Fixes an error where the update_comment is longer than 255 chars and yields an `Data too long for column 'update_comment'` error during the import
=> [BUGFIX] change update_comment to text to prevent data too long error

Resources/Private/Templates/Statistic/Index.html
Without the CDATA I cannot use the BE Module on TYPO3 9
=> [BUGFIX] wrap inline js in cdata to prevent fluid parsing error

Configuration/TCA/tx_t3monitoring_domain_model_client.php, Configuration/TCA/tx_t3monitoring_domain_model_core.php, Configuration/TCA/tx_t3monitoring_domain_model_extension.php, Configuration/TCA/tx_t3monitoring_domain_model_sla.php, Configuration/TCA/tx_t3monitoring_domain_model_tag.php
This patch removes all exclude options of
TCA columns.
The following regex was used to remove the lines:
^.*\b(exclude)\b.*$\n
Fixes: #165
=> [TASK] TCA: remove 'exclude' => true

composer.json
Add the extension key in the composer.json extra section for future TYPO3 versions (https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra).
=> [FEATURE] Add extension key in extra section

Resources/Private/Templates/Client/Show.html
Text for extra dangers, extra warnings and extra info is sometimes not just plain text but HTML. Therefore it needs to be rendered as HTML.
=> [BUGFIX] Fix text formatting in client detail view

Classes/Event/ImportClientDataEvent.php, Classes/Service/Import/BaseImport.php, Classes/Service/Import/ClientImport.php
The t3monitoring_client is easyily extendable with custom data providers by registering them to the providers array: `$GLOBALS['TYPO3_CONF_VARS']['EXT']['t3monitoring_client']['provider'][]`.
To import the data from custom providers, we would like to add an PSR-14 event to the ClientImport class. This way we don't need to override the whole class.
=> Add event for client data import

Classes/Service/DataIntegrity.php
- use inner join to include only versions found in clients
- remove unrestricted setting is_used=1 for all rows
Fixes #221
=> [BUGFIX] fix determination of used core versions
